spring.application.name=e2ee_auth_server
spring.datasource.url=<jdbc datasource url>
spring.datasource.username=<username>
spring.datasource.password=<password>
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE